[profile.default]
optimizer = true
optimizer_runs = 44444444
via_ir = true
ffi = true
solc = '0.8.26'
fs_permissions = [{ access = 'read', path = './'}]
verbosity = 3

[fmt]
line_length = 100
tab_width = 2
quote_style = 'single'
number_underscore = 'thousands'
sort_imports = true

[rpc_endpoints]
sepolia = "${RPC_SEPOLIA}"

[etherscan]
sepolia = { key = "${ETHERSCAN_SEPOLIA_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options