[profile.default]
optimizer = true
optimizer_runs = 44444444
via_ir = true
ffi = true
fs_permissions = [
    { access = 'read', path = './'},
    { access = 'read-write', path = './script/config' },
    { access = 'read-write', path = './snapshots' }
]
verbosity = 3
dynamic_test_linking = true
gas_limit = "18446744073709551615"

[fmt]
line_length = 100
tab_width = 2
quote_style = 'single'
number_underscore = 'thousands'
sort_imports = true

[rpc_endpoints]
sepolia = "${RPC_ETH_SEPOLIA}"
bnb_smart_chain_testnet = "${RPC_BSC_TESTNET}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options